# Generated by Django 3.2 on 2024-05-11 17:55

from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(
                validators=[reviews.validators.title_year_validation],
                verbose_name='Год',
            ),
        ),
    ]
