# Generated by Django 3.2 on 2024-05-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genretitle',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='genretitle',
            old_name='Title',
            new_name='title',
        ),
    ]
